#java  -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ dsl-stub 2.groovy
#java  -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ dsl-stub cli.groovy

java  -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ delete-job yyyy

java  -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ dsl-stub cli2.groovy|java  -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ create-job yyyy
